language: python

sudo: false

script:
    - pelican -s conf.py -o output -t theme content

deploy:
  provider: pages
  repo: SabrinaBernardelli/SabrinaBernardelli.github.io
  target_branch: master
  skip_cleanup: true
  local_dir: output
  github_token: $GITHUB_TOKEN
  on:
    branch: master
